export const Constants = {
  CARD_PERCENTAGE: 0.15,
  MIN_CARD_SIZE: 40,
  MAX_CARD_SIZE: 200,
  INITIAL_BOARD_COLOR: '#FFFFFF',
  FINAL_BOARD_COLOR: '#39CCCC',
  FIRST_CARD_VALUE: 0x1F300,
  MAX_BOARD_SIZE: 38,
  FINAL_MESSAGE: 'You Won!',
  CARD_BACK_IMAGE: '\u2618' // shamrock
};
